name: Master

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Start Server
        run: deno run -A make_website_a_server.ts &

      - name: Use Pa11y
        run: |
          npm i pa11y
          node_modules/.bin/pa11y --ignore "WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail" http://localhost:1337

  browser-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Start server
        run: deno run -A make_website_a_server.ts &

      - name: Browser
        run: deno test -A tests/browser

  formatter:
    # Only one OS is required since fmt is cross platform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Formatter
        run: deno fmt --check

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
      - name: Linter
        run: deno lint

